// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyOrt9smN_Tmn38KsBWjHo5C2iBmSuNI',
    appId: '1:149916884523:android:83d99187a409c5bd52946e',
    messagingSenderId: '149916884523',
    projectId: 'fate-script',
    storageBucket: 'fate-script.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDeKIUjEdd1lVpGvyABz3M1Y3DRMlrT5w',
    appId: '1:149916884523:ios:f43d0b36bcebc16252946e',
    messagingSenderId: '149916884523',
    projectId: 'fate-script',
    storageBucket: 'fate-script.firebasestorage.app',
    androidClientId: '149916884523-sth8iu7lq691a48hdpj8cm5og5hp3gs2.apps.googleusercontent.com',
    iosClientId: '149916884523-o4io4vcdu4pf5m0cp6u0q1ueuu294je0.apps.googleusercontent.com',
    iosBundleId: 'com.unmyeongilgi.unmyeongilgi',
  );
}
